# Generated by Django 5.0 on 2023-12-27 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newpage',
            name='apply',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newpage',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
