# Generated by Django 5.0 on 2023-12-27 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_job_apply_newpage_apply_newpage_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.URLValidator(), django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='newpage',
            name='apply',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.URLValidator(), django.core.validators.EmailValidator()]),
        ),
    ]
