# Generated by Django 5.0 on 2023-12-27 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_job_apply_alter_newpage_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid URL or email.', regex='^(https?://\\S+|\\S+@\\S+)$')]),
        ),
        migrations.AlterField(
            model_name='newpage',
            name='apply',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid URL or email.', regex='^(https?://\\S+|\\S+@\\S+)$')]),
        ),
    ]
